### ISSUE TITLE
Fails to build when used with leptos "0.3", works fine with updated Cargo.toml

### ISSUE THREAD

**Issue by derrickquinn** [tqwewe/leptos_server_signal#1]
Calling `leptos_server_signal::provide_websocket(cx, "ws://localhost:3000/ws")` fails with the current version of `leptos` and `leptos_server_signal`. Error: 
![image](https://github.com/tqwewe/leptos_server_signal/assets/47612550/947bdeda-74d9-4e2b-adc0-f97710ad0d8c)

I've verified that it builds fine, after `leptos_server_signal/Cargo.toml` uses `leptos = "0.3"`.

**Comment by tqwewe** [comment]
I've just published version 0.4.0 of `leptos_server_signal` which uses `leptos 0.3`
