### ISSUE TITLE
Get access to the websocket object to set additional callbacks

### ISSUE THREAD

**Issue by messense** [tqwewe/leptos_server_signal#11]
For example I'd like to call `set_onclose` on it so I can display a warning on page when the websocket disconnects.

**Comment by tqwewe** [comment]
I've added support for this in `0.6.1`.

The `provide_websocket` function now returns a `web_sys::WebSocket`.
`ServerSignalWebSocket` is also public now, so you can use `use_context::<ServerSignalWebSocket>().unwrap().ws()` to get access to the websocket.

```rust
let websocket = provide_websocket("ws://localhost:3000/ws").unwrap();
if let Some(websocket) = websocket {
    websocket.set_onclose(Some(&js_sys::Function::new_no_args("alert('closed')")));
}
```
